package ec.edu.monster.vista;

/**
 *
 * @author Dome
 */
public class DashboardCliente extends javax.swing.JPanel {
    private HomeCliente parentFrame;
    
    /**
     * Creates new form Clients
     */
    public DashboardCliente(HomeCliente parent) {
        initComponents(); 
        this.parentFrame = parent; 
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_products = new ec.edu.monster.vista.ModernButton();
        btn_mycart = new ec.edu.monster.vista.ModernButton();
        btnMyInvoices = new ec.edu.monster.vista.ModernButton();
        jPanel2 = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        lbl_welcome1 = new javax.swing.JLabel();
        lbl_welcome = new javax.swing.JLabel();
        lbl_rol = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(890, 590));
        setPreferredSize(new java.awt.Dimension(890, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CASA.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Britannic Bold", 0, 28)); // NOI18N
        lblTitle.setText("Dashboard");

        lblTitle1.setFont(new java.awt.Font("Britannic Bold", 0, 22)); // NOI18N
        lblTitle1.setText("Accesos Rápidos");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cohete.png"))); // NOI18N

        btn_products.setBackgroundColor(new java.awt.Color(255, 255, 255));
        btn_products.setBorderColor(new java.awt.Color(13, 110, 253));
        btn_products.setBorderRadius(5);
        btn_products.setForegroundColor(new java.awt.Color(13, 110, 253));
        btn_products.setHoverColor(new java.awt.Color(210, 234, 246));
        btn_products.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bolsa Azul 2.png"))); // NOI18N
        btn_products.setPressedColor(new java.awt.Color(51, 153, 255));
        btn_products.setText("<html>Ver Catálogo<br>Explorar Productos</html>");
        btn_products.setToolTipText("");
        btn_products.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_products.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_products.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productsActionPerformed(evt);
            }
        });

        btn_mycart.setBackgroundColor(new java.awt.Color(255, 255, 255));
        btn_mycart.setBorderColor(new java.awt.Color(24, 135, 84));
        btn_mycart.setBorderRadius(5);
        btn_mycart.setForegroundColor(new java.awt.Color(24, 135, 84));
        btn_mycart.setHoverColor(new java.awt.Color(237, 249, 237));
        btn_mycart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Carrito Verde 2.png"))); // NOI18N
        btn_mycart.setText("<html>MI CARRITO<br>Ver y Hacer Compra</html>");
        btn_mycart.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btn_mycart.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_mycart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mycartActionPerformed(evt);
            }
        });

        btnMyInvoices.setBackgroundColor(new java.awt.Color(255, 255, 255));
        btnMyInvoices.setBorderColor(new java.awt.Color(13, 202, 240));
        btnMyInvoices.setBorderRadius(5);
        btnMyInvoices.setForegroundColor(new java.awt.Color(13, 202, 240));
        btnMyInvoices.setHoverColor(new java.awt.Color(242, 252, 255));
        btnMyInvoices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FACTURACELESTE 2.png"))); // NOI18N
        btnMyInvoices.setText("<html>MIS FACTURAS<br>Histórico de Compras</html>");
        btnMyInvoices.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnMyInvoices.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMyInvoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyInvoicesActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(231, 230, 230));

        lblTitle2.setFont(new java.awt.Font("Britannic Bold", 0, 22)); // NOI18N
        lblTitle2.setText("¡Bienvenido a Nuestro Catálogo!");

        lbl_welcome1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_welcome1.setForeground(new java.awt.Color(102, 102, 102));
        lbl_welcome1.setText("Explora nuestro ptoductos y realiza tus compras de forma fácil y rápida");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_welcome1)
                .addGap(79, 79, 79))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(lblTitle2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_welcome1)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        lbl_welcome.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_welcome.setText("Bienvenido, Joel Rivera");

        lbl_rol.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_rol.setText("Rol: CLIENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_welcome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTitle))
                    .addComponent(lbl_rol)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_products, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_mycart, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMyInvoices, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 9, Short.MAX_VALUE)))))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_rol)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_mycart, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_products, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMyInvoices, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productsActionPerformed
        if (parentFrame != null) {

            Products nuevoPanel = new Products(parentFrame);
            parentFrame.showPanel(nuevoPanel);

        } else {
            System.err.println("Error: Dashboard no está asociado a un Home.");
        }
    }//GEN-LAST:event_btn_productsActionPerformed

    private void btn_mycartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mycartActionPerformed
        if (parentFrame != null) {

            MyCart nuevoPanel = new MyCart(parentFrame);
            parentFrame.showPanel(nuevoPanel);

        } else {
            System.err.println("Error: Dashboard no está asociado a un Home.");
        }
    }//GEN-LAST:event_btn_mycartActionPerformed

    private void btnMyInvoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyInvoicesActionPerformed
        if (parentFrame != null) {

            MyInvoices nuevoPanel = new MyInvoices(parentFrame);
            parentFrame.showPanel(nuevoPanel);

        } else {
            System.err.println("Error: Dashboard no está asociado a un Home.");
        }
    }//GEN-LAST:event_btnMyInvoicesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ec.edu.monster.vista.ModernButton btnMyInvoices;
    private ec.edu.monster.vista.ModernButton btn_mycart;
    private ec.edu.monster.vista.ModernButton btn_products;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lbl_rol;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JLabel lbl_welcome1;
    // End of variables declaration//GEN-END:variables
}
